apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml

images:
- name: log-output
  newName: ghcr.io/antief/log-output
  newTag: 4fb11eb540970fef048d68d83b6679b35700de86
