apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/httproute.yaml
- manifests/greeter.yaml
- manifests/greeter-route.yaml
- manifests/waypoint.yaml
- ../ping-pong

images:
- name: greeter-v1
  newName: ghcr.io/antief/log-output
  newTag: 37ba5f74d95bb13692c892ce2b4bea768d154c97-greeter-v1
- name: greeter-v2
  newName: ghcr.io/antief/log-output
  newTag: 37ba5f74d95bb13692c892ce2b4bea768d154c97-greeter-v2
- name: log-output
  newName: ghcr.io/antief/log-output
  newTag: 37ba5f74d95bb13692c892ce2b4bea768d154c97
- name: ping-pong
  newName: dev.local/ping-pong
  newTag: "5.7"
