apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-webhook
    namespace: project
type: Opaque
stringData:
    WEBHOOK_URL: ENC[AES256_GCM,data:4nm3sQKvLR9rI1KTTLvkS1mT03Fz1TtX8bm7oaXSQ0tV+rpRaJfwUEGot8Rf6whRoH1oajAKi+cI,iv:PWeIT8nm6lI8qFycDmVTMQj5nrcrwaOovKvWLoTy7Q4=,tag:bgKvkVp6TXALW93P9l581A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjVycXZXVzYzRU8zZnJm
            aUx3Ylg0MysyYURmaEVWSFhkT09WMTd5b1JRCkdXdmI2bURLdHlmZ1U4OGlEcmlC
            ZDN5dVRsYnZCbWQrUGVZNkZ6eVhXTUEKLS0tIDlHdDVqcHVJNUJWSWlYLzlMcXA5
            REJLL2Q0V3hDMW5zKzJUYUt3T3VLUEEKAuxTcKvzrec8p4CJTTZoPNW6jcREueTl
            vddwIiUWV4s5Pt7kzr/Agn7zxN4YBZnCWe775Supf3xRh+xOmI3FjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19a58q8pvqvv72qhkkgdmuytjgecsyemg7xmdugcc9e0ylm4839rqlzc707
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T08:03:41Z"
    mac: ENC[AES256_GCM,data:xdnEhrJ4d8s7xTEJlyWcrMweqaqqmrcQwGmOegUYJtg4P2CwNGDMCerAmyPlzptwuyHyxSeBs5/T2v3cOQkE6g4J/T6XSgC2UgVzm1Zcb7J4N1v+HrhlUd/Y34chvIFujkoUa4pcEsCoJdJ3GzixOmoC4jh/ZjJz3oDfkag+Al0=,iv:HX0fKgnZm8O056gGFxbLcIqP/Tkm3vvW1hjc9qTFdAQ=,tag:6wqHwvP+COWoY7PrU0iSQQ==,type:str]
    version: 3.13.3
