apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-claim
      containers:
        - name: log-output-writer
          image: log-output:1.11
          imagePullPolicy: IfNotPresent
          command:
            - python
            - writer.py
          env:
            - name: OUTPUT_FILE
              value: /usr/src/app/files/output.txt
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files

        - name: log-output-reader
          image: log-output:1.11
          imagePullPolicy: IfNotPresent
          command:
            - python
            - app.py
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: OUTPUT_FILE
              value: /usr/src/app/files/output.txt
            - name: PING_PONG_FILE
              value: /usr/src/app/files/ping-pong.txt
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/files
