apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-data
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: log-output:2.1
          imagePullPolicy: IfNotPresent
          command:
            - python
            - writer.py
          env:
            - name: OUTPUT_FILE
              value: /usr/src/app/files/output.txt
          volumeMounts:
            - name: log-data
              mountPath: /usr/src/app/files

        - name: log-output-reader
          image: log-output:2.1
          imagePullPolicy: IfNotPresent
          command:
            - python
            - app.py
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: OUTPUT_FILE
              value: /usr/src/app/files/output.txt
            - name: PING_PONG_URL
              value: http://ping-pong-svc:8000/pings
          volumeMounts:
            - name: log-data
              mountPath: /usr/src/app/files
