apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-cpu
  namespace: exercises
spec:
  metrics:
    - name: namespace-cpu-rate
      initialDelay: 5m
      successCondition: result < 0.1
      provider:
        prometheus:
          address: http://prom-prometheus-server.monitoring.svc.cluster.local:80
          query: |
            scalar(
              sum(
                rate(
                  container_cpu_usage_seconds_total{
                    namespace="exercises",
                    container!=""
                  }[5m]
                )
              )
            )
