apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
- namespace.yaml
images:
- name: ghcr.io/antief/broadcaster
  newName: ghcr.io/antief/broadcaster
  newTag: b7118e6b4ae1eca526423a826b85df7daebd4ee5
- name: ghcr.io/antief/todo-app
  newName: ghcr.io/antief/todo-app
  newTag: b7118e6b4ae1eca526423a826b85df7daebd4ee5
- name: ghcr.io/antief/todo-backend
  newName: ghcr.io/antief/todo-backend
  newTag: b7118e6b4ae1eca526423a826b85df7daebd4ee5
patches:
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
  target:
    kind: PersistentVolumeClaim
    name: todo-image-claim
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: staging.todo.local
  target:
    kind: Ingress
    name: course-ingress
- path: broadcaster.yaml
- path: backend.yaml
