apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- namespace.yaml
- backup.yaml
images:
- name: ghcr.io/antief/broadcaster
  newName: ghcr.io/antief/broadcaster
  newTag: 7c7c27c448ac9857a56e519a50363583e0e15d16
- name: ghcr.io/antief/todo-app
  newName: ghcr.io/antief/todo-app
  newTag: 7c7c27c448ac9857a56e519a50363583e0e15d16
- name: ghcr.io/antief/todo-backend
  newName: ghcr.io/antief/todo-backend
  newTag: 7c7c27c448ac9857a56e519a50363583e0e15d16
patches:
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-path
  target:
    kind: PersistentVolumeClaim
    name: todo-image-claim
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: production.todo.local
  target:
    kind: Ingress
    name: course-ingress
- path: broadcaster.yaml
- path: backend.yaml
