apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18.0
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: todo-postgres-config

            - secretRef:
                name: todo-postgres-secret

          command:
            - sh
            - -c
            - |
              until PGPASSWORD="$POSTGRES_PASSWORD" psql \
                -h "$POSTGRES_HOST" \
                -p "$POSTGRES_PORT" \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB" \
                -c 'SELECT 1' \
                >/dev/null 2>&1
              do
                echo "Waiting for PostgreSQL"
                sleep 2
              done

      containers:
        - name: todo-backend
          image: todo-backend:2.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000

          env:
            - name: HOST
              value: 0.0.0.0

            - name: PORT
              value: "8000"

          envFrom:
            - configMapRef:
                name: todo-postgres-config

            - secretRef:
                name: todo-postgres-secret
