apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XuJjygZwCm+EVPv6ZHEVhbrGCMStWsRY/fvuN/6W0H0cISicAbcaqfGc2YaqFzG9clkSLEIV7fScW2AI,iv:p+TrdUbCV3pY4/nHOdWNy0YD+STVwRs3k4wiAihMYF8=,tag:NL/fl/CQ0J3qNQrJda0orQ==,type:str]
kind: Secret
metadata:
    name: todo-postgres-secret
    namespace: project
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeEJmczlFR09IOEhVUlpM
            T2ZGN1NoYjRVNEpSSWNqT1dWNlBZOGY3Qkc0ClY4VkhLUW9yYmwxL2tYWXJ5Z29u
            ejZCSCtKd0hNdm05SCtHQnJxZ1lrREUKLS0tIGgzanVWYWt3M20wTlIzNjdMellu
            Y0FCczRUcndwbjhMclRxTDZta0J6L0EK8obeyhqx8M3wdN491Is1YviPUg7atdu/
            qctQnrwquBpeOAK0zOr4k3ekjKWGlWmhmgMonFqyTL3oLjPyaBvk6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19a58q8pvqvv72qhkkgdmuytjgecsyemg7xmdugcc9e0ylm4839rqlzc707
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-08T10:40:42Z"
    mac: ENC[AES256_GCM,data:hyNKAx8MNdK93bOQ204sx/re407JrK99HSu24Vrg6hQGH//ba5qEsxz1Foxpjh0MghTtmX8tenZRnvunshZQCL6h+oT678ctbigo3y8kaOTn6XO27gAWRf/2iPJ5z6fVdKtlD9x0rgbwpT77Qg8VL0HebG56u3+MKupsvD5Qkpg=,iv:MThRqOTrkPOMh4WRSL2lzyZcTFlmT1Hx7st0cYDTtO0=,tag:DGhjSgr9TyRGV7M73Ihf6Q==,type:str]
    version: 3.13.2
