apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- ../todo-backend
- ../todo-app
- ../broadcaster
images:
- name: broadcaster
  newName: ghcr.io/antief/broadcaster
  newTag: b3e3f3040d1c6785c50a2fafae71b5b427fd93f0
- name: todo-app
  newName: ghcr.io/antief/todo-app
  newTag: b3e3f3040d1c6785c50a2fafae71b5b427fd93f0
- name: todo-backend
  newName: ghcr.io/antief/todo-backend
  newTag: b3e3f3040d1c6785c50a2fafae71b5b427fd93f0
